nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: A REST API BileMo with Symfony for OCR
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token
                    operationId: postCredentialsItem
                    summary: CREATE JWT TOKEN FOR AUTHENTICATION.
                    requestBody:
                        description: Create a new JWT Token
                        content:
                            application/json:
                                schema:
                                    $ref: "#/components/schemas/Credentials"
                    responses:
                        "200":
                            description: Generate token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: "#/components/schemas/Token"
            /api/users:
                post:
                    operationId: postUserItem
                    summary: CREATE NEW USER
                    requestBody:
                        description: Create a new user
                        content:
                            application/json:
                                schema:
                                    $ref: "#/components/schemas/UserData"
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: Client email xxx@xxxx.com
                        password:
                            type: string
                            default: yourPassword
                UserData:
                    type: object
                    properties:
                        email:
                            type: string
                            default: xxx@xxxx.com
                        firstname:
                            type: string
                            default: yourFirstName
                        secondname:
                            type: string
                            default: yourScondName
                        address:
                            type: string
                            default: your address
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
